# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'frontend' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for frontend

  target 'frontendTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'FBSnapshotTestCase', '~>2.1.1'
  end

end
